networks:
  mysql:
    driver: bridge

services:
  mysql0:
    image: mysql:8
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency
    volumes:
      - ./data/mysql0:/var/lib/mysql
      - ./shs:/root/shs
    networks:
      - mysql

  mysql1:
    image: mysql:8
    ports:
      - "23307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    command:
      --server-id=2
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency
    volumes:
      - ./data/mysql1:/var/lib/mysql
      - ./shs:/root/shs
    networks:
      - mysql
    depends_on:
      - mysql0
